server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/user/**
        - id: Contact-Service
          uri: lb://Contact-Service
          predicates:
            - Path=/contact/**